services:
- docker
language: python
python: 3.6
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
  - secure: XzWSAz7gCZRHnMjS95+Nj90ZJTxQ6M6Xh2gydjwV1CZCtnudOezCQOxqWCBqcEWVbrD/UOGfROTYn4gAaYp3iLkdF9AKF30yoQ/BDH1ZlpUMoeTnoF1LwZ4gvLGU2agez2WxfoHe5mpp2BX7POfRgDwyeuWjrRC7WSXHEnQly73NfQqT72Md9BPUXJ9Lwvv2w3HvcBv2dBGIW9LoTOg+pTeCmf73XBM/O4TPaE7DPuY1Txi1rg6//Si0NT1Mcr5TZ/zcpVXeKKodT3Tv62X719vHiu0tY5Vtsz2MuClM6g9V2tpHVv0p6c8dVM3zc8nbdOhpBOD56D9h8+f15soXO9d651Ekh1WUAo95DVFJd8BOqCktOterFhlpvU+HFaeGCNZz/kLLasBDBIGlJkNgeYGZFx0dwpmt88/0tqfbvPrANtMK6Ax1oGmTymKZQCjwdPbeARz+aI/h1cLxZH4+6WtmlDY9tyEwqq0EoUUHI8J4lOfl3GceSXAx+wfHsvWOMABQ0yMlXzve7Dxk24a7jTf/VzXtdw+lJ2DbCGEIwnsx8Vn3bscCzyebdqWynL3f3XzfJXM6LF1KBnMgBNb2RxM4hNAy5kVf5jjJT1bVJnD8icrMjhEwbgJ3JfLSQQGj0UsZesaol+kcsjW+RQcycKFjVS98644bNPBD1NPIg9A=
  - secure: epWtBZwjVbkaiL957R4yyOKzXc8i1oYQghFWJnKhW3O8qfPyB069MH5ewcS4jBdn/jN6GPMaeVTi4esxtftTy8EWp3LbcQWHn3+NZiDNC3I43lSGxGyz+ARgI1ey0gGxQSYsu1TKHthcSkJEAhFcQDQIqigiXLqRD1lB4Tp1h7W+Mi/Of0G1btjlTG76h4u4w8HbZ6BJab5Zc9jXjGDOcLPg3FnsNEz6CPlF3+TOmoHcvfhDm+JNaA6l1vl6RS1oOlQEO+Qx3fsqg6OxsOk+vnJbox0g1c8syAf3bbc+WJPRYWWjZdRiddh5mahfAI+NSWrQLw00TA2w0hXCjUc2UHU3mGLhzQ3HCTtBLQxuqd7MN6IPsinFhAM4+aTV4cC803V7ZSrEfEkOeIZ91OyEaNoqfI4BTCD9dBkM4VtXcagtejGKtyx05AvxCoQC7vAOZiaBOuYFqAFEcvbBdcYKV/3CLsg4WN0Dzpq/8OefQaqKX3LKaDCH0GJbv2sWBUTli/eOyHO+IkL4FItwWuCGGZdMf7DGqh/G1pKJfABVUeMZQRGbQpYJU7oOyYcast3I3sZsWif5YH0AAJf+sC1U5Ck+pkM4iN7l/6F8Z8lUvwwnMzWDuMu1MX9iSuotBrmuvV6sH5YVdfRQKgqWNqZxt72fHTCAg4/AjL4cfyUhqTQ=
install:
- pip install --upgrade pip
- pip install -r requirements-build.txt
- nb setup
script:
- nb push
