sudo: true
language: python
python: 3.7
env:
  global:
  - secure: tXXAXMcsuLzCHZuIKv22Fi61cxMVGkUY13AYPgJelXRw5XGiV1Lf+yfRSR3BHk9YBF+vRWb3P7rY/TObpr+RE7cwq1oalwkobroe1XrAEYhE1AVPqDhvSDxVZ5+ytpuvhTowaAafJVmAyTU1Mh4m3Nk0MJhy5MUH75zM3UjHrZxbVUoAVtYRweKpux77NyfLWjhijXEWs8Dcd26gYJbqvP5bKTTtxameR1k9DfhNjgWp/hDaPHfkCVbzA/ONqgonknTd8cG7SKA3G2Jn8XMYDHD7e09prLTKvgYEps1nItMNe81e21e8LKFAmpt9ja3dJ7/EhoPmeVD2LDTSNoU+QdIW0dQLFGIJKgdQXt3+RCbYCVz+eNrt7ZdwGTdkEQMiIemr4ydaaL0RRef0tavToBSsKGv+Td/xin1hH9OJnwrtuuNjuWJuGXV8byn/WTAQ0tiVWzUTepoHAH3JKktfAc9ysqNPuWy8Tdx23ItP/xWeBjXfTGdlsF22e06jUiTs0+OXoHFmUi39ZcW35XzkDnq0dUIda4rwom1Q8cWyA6kG4ECOXZWc3m0d6QKd9JeaTPv36u8QlOtl8Un27FL9k/PD9SP47l9EZg80oFuqK0NGuBZQ9ADR5Uw5Xix5cXHXM/DtlgzEwS2E0l0xuUdLnFhwzr53p1VJhf/8RpkmkIU=
  - secure: yY0+vvqYuMfLCv+GzxRUrVeKiMPe0v0YD7dtJzVrFFT99MWHSI7JAA0evWr3FYwro7025ANWsqZOKFxPaYqBkab7kZ+k8/CNBCN6UXnx8aiUG4Q+rWcqydW2HXcLgY0XP58n5LowlmA/h41g+c5YgECaLRN+i/jEoAoKU39dVvHPBf29m8OflP0QMSHguh1aQ5WRLlLxu0xAQknEa55NbnIF6vVaaI41A7DkYkFeTXJADFO/2LOIX1MHdVMR5rWVQtXa2vTg+fzptKuaeIAqYGzP602FalI/FExwjr4qZORSD4hL7noSaRF1G4CfuMNLgHQqy5rQTv8HUpQysuTSRd8FMz4WGf1C7VLkAFlKsqUwnIr2E3rnxeaycCdv3h2xKpN+EVR+xFB/gZHkjsmRVqnL5A6gSgJ2+ua8qvZLrsULZO4j99GqBE5659LwdqAtDzZd4TzUNddlk26D/xn6WwhwfxR/iCPo/fShgbtPYWgMW4u8tLggbN/tkVz49YNYhTD+u23HCvMLPN7vsZKA8QVUZZFc1q8yJ24DMe4TaCU6k0Pksf4biTg7poOJcv7uabZJH8gMqY2kjunY/d3EwuBjFNRVZqpiXRcu2MHK9pXJA5CwQAiovkrf/5qJOTyW9TUFBEiEKDWWg7HeBRznyrjaPc6Mjk9G3+bWW14+GcE=
install:
- pip install --upgrade pip
- pip install -r requirements-build.txt
script:
- nb push
