services:
- docker
language: python
python: 3.6
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
  - secure: Cco+lzozWJP6ikmg1Sqer5h3RaBjED7L/9Poz3A2rbBqImS112fBD3gt4wMV5J1HvpdhxEVSghQYMdL8icq3o3cq2YiDXMk80ICJSWaxV6tuL+YQqCbxvBxdj8lAUfQA1CUVPHwqI/Pj/ggxVkKP9u09xr5eCmKItTpKn6noPF+RlgbjjHBHwh4kzmfetQMhiip7nE5el7txX7oyh0gNioy/TTrLoZHmxvRSuOfU+i/jrofGQTh3jU+ZuWPEK1ciUTxOAgGsuCgBYMy0+WsnEe8O8ZQzOx/01GXglcJLqHDo2VlLHdT0A67ixStXoxBXtiMd9ssHrCAbU0hq7L5UZkshV5zRfQ1YUqfsT+7po4rgAep63k8d6PlQlSV8pij8B0bLbGWCxS4hxe0GziSUyBlmfRl0Qkk+ULzS5rtN+eBidQLGbWAvomlXIzFDMjmz6QlN0RXNWY72uK+aECavQ4RfBRb/rNQJ3mHtQvbAjF67R4CoM3FFQvx/X11dNmunrtimHRToL4KXgwqjDXXk9QaNrYouXWyScmEXhhA+9zoOJmNkskw9KLtL58Xg4klWOYI9sxycAUmTmgWEayGIyR9T6S5m8NWttCiuZgrhPWGxS/qVOnW0b4GwfcjB3CvPrtCBtliJ8jK00X4Vm7pPnBKH64bYfOuYDLKQwZmJRyg=
  - secure: gSHO6Ie2YBn+aSE2LlUIqQj45rkba73x18ywW9U+oNnb5U8ZE/4HOawowj4vm7IuywvFWipwBzlbLczva14FNLuBJCIRvX3/jjDAZQNDQk1HNdzPW+mnY1sJP9GFbq6tht2S40rngBA/QTtJI8yisFZAkR4wDqjeBmBOX9bdqY26Yy/3XjR0OjU63Vk38/ZBgAKfxVAcTLBCAu/Rez/Sakhf/zfWNEqQGpFFn7XW+WzVZHKFaAid6xVulBqCLuVdMurH2fFb4whkAMpwEV+CpJrzAB8fjdqVVyuw0GM8WIimunJh5q2zVv03HY8FT5GQ/E74Irpi1I77fPVfhd/e+e5kq2np9OJurmc9N2jQ9u1LeypDz/pZ4OrhxsuyaUZGyMP8U3ly+1wOij5zMs3nv+9Dv3d1SZjT8Iv7H3mpuK6WzZhf8JRV4E2lPAvoXq10WnXOnWYYQXKDjBGgr1GMRcec+zQ3IMjAYpT2VJ9OF6z1Usf1jx1U7ZWywDEwUsCtUfGAmjhUwHMnez89Xi2I/8FvTHUqaKvnwSHzsm0pCNMiElVO3bvoQLQObEkuCfylx78sYL5wf/kfqGxx+ENLEz63Kgye6k2VsUtIaV57sIY8E7q5/JF10i9eS4IQJ08kT2kPoyVw2/25Zba7BDyrdFo9EOyRMSF8Tjy0r+dAXL8=
install:
- pip install --upgrade pip
- pip install -r requirements-build.txt
- nb setup
script:
- nb push
