services:
- docker
language: python
python: 3.6
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
  - secure: a0EDV8+/q33pN6ECfhsGA8/0UNELZF+pxUJFXmZKPD8H/ts+Fy7kDC9n5XxMa12JFMpapy8FcVnlP+Gc7FE0QDye+aV5GRoENniCFySY8yffgEGS7/OddEj30ZDebaMrNtSosdtMQbExk0VO+qqJs8MOOnBh1YrBoPu3BVOA3ETR7a/jnsSgiSz6PhkAOKBouhNiZ8c1UZmLqEJEiFWxaG80L4Z/O0/8EAPfls6rq+EdZXdTeFgvKiIx2SVbuweHznMIW95e7fWUUtz9vdHh1ddvgz8kYaLXklOS//LwGfplR9hvXm6+IPuvzbsS9TQ10gCTygWUs1Zn1b89mN7OpGNfr/j3LLDWldG7+GzsY09aCNmKA/GSYjC1O/oIrWIbggRPXj2AmD8TDmCcWaECLazKZhTTj9qcdpQMZBXNj3zvwUqe63ugwPH/MkmQbgXsilE283OCTlVEBbClx9KUMHIe+OCxYKtQTIVNWltkOVlLLl9YV81qIJOStgt7gq23bQFQsuaTLxNOxVzpxvNKr/ZWiGEkv3u1tHyTir5X/3Hz+h5uDTv8U3+L5A3OyF7EWMZ+4f/qrgU8hpklw/uzixgNrzWx6Swbn+CnMMyP3RubJtI7tes4h9ZOKUAvIW+xeCFqzCvwK2zWNtITcUedSm6H4A8gBL2lyB54cBeuZqM=
  - secure: KkcGedWsyrfnJvmcmSABQnSSUyL/SLJmQcHcydP8IYq2PZbbSyXUBQB2VV9az4TRMm3/36aM8LFO3KKkljYWvhsQgqwpeh9nzSsdiSOpL00MMDU822AjN03nVbIszmFtprN7tnyAaToVM0SVo1iYuMmQV4VmbtgdnWYn8Wv3S5Lr7XzFtacJ922MwUHa3nfGs7g6uGm0J0krysoidzRCb+LWU9nMJ4JYKn2Za2T3gQN0SF/IxmSdHAY7yemTWKXXSw3euwSRh1EN8JHdmjU3XJ3ASsJcISq97rrV5CDaH11Noecu2kVmmQZCM0zZw5KiA6CYUYFCAlYUXnFKe1/gOwOrTGalH9gg7TwtJqAIZJ23L24v/p63KWP/hVojOSfS+hXAbGtjIeV8ZPSjafClzS2UM0m68Dltwv3ZBy2v9n7Bk+3M1bOyL2HB+Lo+uloGQ2KaOMMtfwP1pGkONSkskzq0k7LXGBYOWnVnbUA8K8R+5OUtOfB/624NoMNAlCd2M93NRiGC0trKG7gkacA5H/J5OIKFcbS+dKd0RdXxhEGffFC1TUAcJAoG8KsOOgJZ5z2if7TMKEkPsw74NG2fmll36Hzyfp5084FtL/Jj7UystYDoETd5IiWiM3QRk98lsgi9YiL653gjyaqULMsS+gHiZMoBCFudFiDW7NVOzPM=
install:
- pip install --upgrade pip
- pip install -r requirements-build.txt
- nb setup
script:
- nb push
