services:
- docker
language: python
python: 3.6
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
  - secure: SBwCGVggIn1YMLmqavo/JIG13vtMNdgOjLuRIMMw3ennPr5aveeETvBEREnKkrJESyhVTVvi9177l0NII+mNoKFNPLtIMKs6BDGx1DUHxFbEe3LEhKrfsWMzrhcSSqLsrRjunfB2+kOcuEJGchMDVtr2Ky+UJreMdj6fhsMcZ7fw2ftshpZk9eYkN+2uPlT8UnZhYmIdvfYP7w4hky8gXguuKf1iVvVDjPVKFsuY2rwokRoHR6p4igozZ5DEmkNonCnlwr8uFf2+crhipbRc7wTWcUZHjvcUlsr5gYeZ81hEfvf1wMN0WXZ9okRg0cJ9rXZ3Zk0iFXfZ11K1s+sEYVOXANdQI49gnW2yEDY9Z0YvB6BRNK/7C2QtW54rzgrcrf8ZG33EFrjZ03KpeRjSBNZJeNZvwhU/h9OP7YQzJsZrTNdLRxFEYWQG9eBJAc1UxtOs+2bKBNF9AYrEsIz6dFVRhVlWIPyWsR78lDxPGQvi7n7ihzvMAAhMn6tvo82Fn2BfT8pTIg0tvFLgDRN9uxmCVSlc02+RXb28Y1F1LZmHM0yTPLF6sEvq+mdoXJz+F8ubb8Iri33/C2LND8iUrfSc84F8Z4Exlo4cbtKc3ELXUlpCn72+dW7kieMvjDozP6HBCA0afopdGYLo68rJ1U4JfzX1MGbBY2xS5C22528=
  - secure: TjtWVVCE91bfvEuV0vfkaBeU1IwxzVstPVyYIqdCNnE+++GR2oasANvclkqT3qNde5sAR79rxDqMH5isoT/faBLnYhYgIQyLtFf29azKbrE7mK0D7r2B6W3BFVsiE4aJhKYBpLJSov8KT1ogeukDbDDzxcl5dVL6oAJSjyt0UuUUhHBl1iWklIi/e7xTaYGS77v4oECpmhv8xYhqe/NlsH8U8Xyv2H92WhnJymC2+1buPVUxkk8zWwUBeIU/XP8uqel5x4IY5VFF1+/nQn4eBqUEj/rlckgGkOXHYId3XKZrKn94gE6sz6f9droj1XjO7vKOI3CUgtsJgk7r50+2b238qAGoAzXqvzxOd9+ulD+aqecMSbVWVgnGB7z8zfgrHVhHtYi3N4tMguQSoD4kf8HL7LZcca1EW162QS4Th6l1ATrOv7OnJt9/Jnc7WsKbfKXQ5OP+RlUVxHfXKGAEuVRBy52lLmPs068ohAn0xuXW9ao7Bsz7jAMU0Haa5uRhfeskUqhRvnPkFlU8UTm5g2QveludmsHLLnK/7x1VsyctOZY3NA2m7G2auqQOFH7aVOEcTKa2vLW14C2t9O8rlb3ESuy0J9rP1AeBg1MmP8m70XKY5suE1fYH68LWdyidNj7EDjNhVWWVrjo6QDXP+FSQQGtSDwpJtpiuUMquG9c=
install:
- pip install --upgrade pip
- pip install -r requirements-build.txt
- nb setup
script:
- nb push
