services:
- docker
language: python
python: 3.6
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
  - secure: SBBO63AlkfzVs/5LsDYSlQcSdvjM9/4T7fsmjUYNRUkMdSKfirdPejid4Zf0KL5yxJA54KJUmODUOFqztcIw+XTyfKOIUYfQVkHCWDTdxEAzDri1zrny+WAHFOpqg3oQHGmvfpP16wxv60cJ354JLfloqaMjudsq8qbBYaEULzJiIPDHHcyN5V2AKrL9lxkha5InpimMi2wdOP0AxHJPeJ4WI94qE6yRBUrvEyEtufsTW1ZJ6NnXjJE+KCw5BbJHnoPibIit4cf+lCZWNVn0a9hPfqnuVSM5xpcU0d2esOl/bdBzHkINGn/GGhnI1Ei3TRKXdCYUOHuxypJfAwRNoZINsEjOpAIIHrGhkHPp5RcWKB3WbvgJK31augWoTVOrTD68MInUthSfc8WxuUJohLGNULCe4iHa+Em8Z2lk1DJLz8/BGgPS1oKurdwolVNHoxzvTAqP6LoVJv3PjCAdCT+xgelsU9unIP8MmricgfmbRyE9te/sc/WLmfrH1F2pLeV2vrOxEnGcF5SgM3Oh29a5zV+dVw4b4U4G3kUWMIV6hUGpQpAf3BN2kmVUaSv9reDIh9ycWVJcUzoZMUE/ED5Lrh7iTtuWuYroane4Z+HRHYPaJX1C/uZuc3ZpoDizHAYuGi41Kogz6P2jE/pgpPBONwd+/Lrsgpp0krE9WPM=
  - secure: moY035rpcJp22diHzozl2awZmBHHflaHO2k3S72PZm8BSbqiRMo7g/WWcV7lJ+P/XwU81kduPcRpEMPedr3qx5T7tjHOVAizfje0zqh2AjM1wxGvMyZhRxK4y4kwQQDZQdwbJgeBUTcWn1ppxY4sA4d58djZDGpUwqwOMIGXPJRoo2EF6RF+xiDNN6MCUXqk8LqeQtYay3fdXb4rvUVBvA4t+y1Ctto873+ImhavJLnfo65vcRmwj4093hMwz8G+WJo7QFAR5HJHLop8FPZcCJdf4X9XHrtP6UYZJgT+/UiCDZ7o3jVLtRCRZu72HLhzLSVA0kC2LcOtGwfCyxHqv2UWgqsF4ADytmEPmRC2ZJLTqAxUszQEX8YFHYMqtlX9+MiLi+tq4wd50G0lusXJAK+kz79TTCrs1jbTQMu+yeKwaEIKRcjay/0kRcG+TZV1VZ8sF5kSVIuPTGudv/WbxZupixoESr40dzTuhD/cigrjSR37zTEzxUnDzNiYjOAb2ol6ZQYu5H0GQAgMQDBGCsPHU4urY7fPu5jmp358gPHMIrBwXmF2UsuaPlhSEYURB3lmmnjtyS1oEwIjpSOrXxnl5u/DLAolD5ONWHSjEcuz8jhAE4EYLT/LwnzTqphmEM8WCTUzXf34BP8BDMJZdan5NIQko8sCNGwDtStPmkc=
install:
- pip install --upgrade pip
- pip install -r requirements-build.txt
- nb setup
script:
- nb push
